
#include <stdint.h>

#define RCC_BASE (0x40023800)


#define RCC_CR_OFFSET			(0x00U)
#define RCC_PLLCFGR_OFFSET		(0x04U)
#define RCC_CFGR_OFFSET			(0x08U)
#define RCC_CIR_OFFSET			(0x0CU)
#define RCC_AHB1RSTR_OFFSET		(0x10U)
#define RCC_AHB2RSTR_OFFSET		(0x14U)
#define RCC_AHB3RSTR_OFFSET		(0x18U)
#define RCC_APB1RSTR_OFFSET		(0x20U)
#define RCC_APB2RSTR_OFFSET		(0x24U)
#define RCC_AHB1ENR_OFFSET		(0x30U)
#define RCC_AHB2ENR_OFFSET		(0x34U)
#define RCC_AHB3ENR_OFFSET		(0x38U)
#define RCC_APB1ENR_OFFSET		(0x40U)
#define RCC_APB2ENR_OFFSET		(0x44U)

#define RCC_CR 			(*(volatile uint32_t*)(RCC_BASE + RCC_CR_OFFSET))
#define RCC_PLLCFGR 	(*(volatile uint32_t*)(RCC_BASE + RCC_PLLCFGR_OFFSET))
#define RCC_CFGR	 	(*(volatile uint32_t*)(RCC_BASE + RCC_CFGR_OFFSET))
#define RCC_AHB1ENR	 	(*(volatile uint32_t*)(RCC_BASE + RCC_AHB1ENR_OFFSET))
#define RCC_APB1ENR	 	(*(volatile uint32_t*)(RCC_BASE + RCC_APB1ENR_OFFSET))


#define GPIO_PORT_MODER_OFFSET			(0x00U)
#define GPIO_PORT_OTYPER_OFFSET			(0x04U)
#define GPIO_PORT_OSPEEDR_OFFSET		(0x08U)
#define GPIO_PORT_PUPDR_OFFSET			(0x0CU)
#define GPIO_PORT_IDR_OFFSET			(0x10U)
#define GPIO_PORT_ODR_OFFSET			(0x14U)
#define GPIO_PORT_BSRR_OFFSET			(0x18U)
#define GPIO_PORT_LCKR_OFFSET			(0x1CU)
#define GPIO_PORT_AFRL_OFFSET			(0x20U)
#define GPIO_PORT_AFRH_OFFSET			(0x24U)


#define PORTA_BASE (0x40020000)

#define GPIOA_MODER		(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_MODER_OFFSET))
#define GPIOA_OTYPER	(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_OTYPER_OFFSET))
#define GPIOA_OSPEEDR	(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_OSPEEDR_OFFSET))
#define GPIOA_PUPDR		(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_PUPDR_OFFSET))
#define GPIOA_ODR		(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_ODR_OFFSET))
#define GPIOA_BSRR		(*(volatile uint32_t*)(PORTA_BASE + GPIO_PORT_BSRR_OFFSET))
